blogspace/accounts/urls.py
from django.urls import path, re_path
from . import views

app_name = 'accounts'

urlpatterns = [
    re_path('^register/$', views.register_view, name='register'),
    re_path('^login/$', views.login_view, name='login'),
    re_path('^logout/$', views.logout_view, name='logout')
]

blogspace/articles/urls.py
from django.urls import path, re_path
from . import views

app_name = 'articles'

urlpatterns = [
    re_path('^$', views.article_list, name='list'),
    re_path('^create/$', views.article_create, name='create'),
    # Slug can be with any len of alphnum or -
    # Url param capturing using ?P<>
    re_path('^(?P<slug>[\w-]+)/$', views.article_detail, name='detail')
]

blogspace/blogspace/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from . import views
from articles import views as article_views
# Allows django to define where static files are
from django.contrib.staticfiles.urls import staticfiles_urlpatterns, static
from django.conf import settings

# Use re_path in future for regex matchings
urlpatterns = [
    re_path('^admin/', admin.site.urls),
    re_path('^articles/', include('articles.urls')),
    re_path('^accounts/', include('accounts.urls')),
    re_path('^about/$', views.about),
    re_path('^$', article_views.article_list),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

blogspace/accounts/models.py
from django.db import models

# Create your models here.

blogspace/articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    title = models.CharField(max_length = 100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add = True)
    thumbnail = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def preview(self):
        if len(self.body) > 50:
            return self.body[:50] + '...'
        else:
            return self.body

blogspace/articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'slug', 'body', 'thumbnail']

blogspace/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def register_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('articles:list')
    else:
        form = UserCreationForm()

    return render(request, 'accounts/register.html', {'form':form})

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # Login the user
            user = form.get_user()
            login(request, user)

            # Check that next is inside the POST request
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
                return redirect('articles:list')
    else:
        form = AuthenticationForm()

    return render(request, 'accounts/login.html', {'form':form})

def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('articles:list')

blogspace/articles/views.py
from django.shortcuts import render, redirect
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles' : articles})

def article_detail(request, slug):
    article = Article.objects.get(slug = slug)
    return render(request, 'articles/article_detail.html', {'article' : article})

@login_required(login_url='accounts:login')
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # Add user to form and save to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', {'form' : form})

blogspace/blogspace/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    return render(request, 'about.html')

blogspace/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Login</h1>
<form class="site-form" action="{% url 'accounts:login' %}" method="POST">
  {% csrf_token %}
  {{ form }}

  {% if request.GET.next %}
    <input type="hidden" name="next" value="{{ request.GET.next }}">
  {% endif %}

  <div class="center">
    <input type="submit" value="Login">
  </div>
</form>
{% endblock %}

blogspace/accounts/templates/accounts/register.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Register</h1>
<form class="site-form" action="{% url 'accounts:register' %}" method="POST">
  {% csrf_token %}
  {{ form }}
  <div class="center">
    <input type="submit" value="Register">
  </div>
</form>
{% endblock %}

blogspace/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% load static %}


{% block content %}
<div class="article-create">
  <h1>Create an Awesome New Article</h1>
  <form class="site-form" action="{% url 'articles:create' %}" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <div class="center">
      <input type="submit" value="Create">
    </div>
  </form>
</div>
<script src="{% static 'slugify.js' %}"></script>


{% endblock %}

blogspace/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{ article.thumbnail.url }}" alt="placeholder">
    <h1>{{ article.title }}</h1>
    <p>{{ article.body }}</p>
    <p>{{ article.date }}</p>
  </div>
</div>

{% endblock %}

blogspace/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Articles</h1>

<div class="articles">
  {% for article in articles %}
  <div class="article">
    <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{article.title}}</a></h2>
    <p>{{article.slug}}</p>
    <p>{{article.preview}}</p>
    <p>{{article.date}}</p>
    <p class="author">Posted by {{article.author.username}}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

blogspace/blogspace/templates/about.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>About</title>
  </head>
  <body>
    <h1>About Us</h1>
    <p>We like django</p>
  </body>
</html>

blogspace/blogspace/templates/base_layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
  <meta charset="utf-8">
  <title>BlogSpace</title>
  <link rel="stylesheet" href="{% static 'styles.css' %}">
</head>

<body>
  <header class="wrapper">
    <h1>
      <a href="{% url 'articles:list' %}">
        <img src="{% static 'logo.svg' %}" alt="BlogSpace">
      </a>
    </h1>

    <nav>
      <ul>
        {% if user.is_authenticated %}
        <li>
          <a href="{% url 'articles:create' %}" class="highlight">Create Article</a>
        </li>

        <li>
          <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
            {% csrf_token %}
            <button type="submit">Logout</button>
          </form>
        </li>
        {% else %}
        <li>
          <a href="{% url 'accounts:login' %}" class="highlight">Login</a>
        </li>
        <li>
          <a href="{% url 'accounts:register' %}" class="highlight">Register</a>
        </li>
        {% endif %}

      </ul>
    </nav>
  </header>

  <div class="wrapper">
    {% block content %}
    {% endblock %}
  </div>
</body>

</html>

blogspace/blogspace/templates/homepage.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Homepage</title>
  </head>
  <body>
    <h1>This is the homepage.</h1>
    <p>Welcome to blogspace.</p>
  </body>
</html>